# Generated by Django 5.2.10 on 2026-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=255)),
                ('lazy_prompt', models.TextField()),
                ('enhanced_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Prompt',
                'verbose_name_plural': 'Saved Prompts',
            },
        ),
    ]
